version: "3.7"

networks:
  net:
    driver: bridge

volumes:
  db-data:

services:
  postgres:
    container_name: datos-gob-postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net
    ports:
      - 5432:5432
